### ISSUE TITLE
Display user name for each statement

### ISSUE THREAD

**Issue by cdxker** [arguflow/app#73]
This might possibly need some UX work, but the implementation is simple
![image](https://user-images.githubusercontent.com/32852291/223296991-563168fb-205a-4987-98d8-c2c7178c0522.png)

Current view, a name being added using nostr metadata could be a good addition to see who made which post

- [x] Show names for each statement/ post
- [x] Show names at top level topic

**Comment by fastfists** [comment]
Only displaying public key at the moment since displaying metadata will require TONS of connections.
