### ISSUE TITLE
UI Design: User management popup for topics 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/app#83]
We should support the following features here: 

- [ ] button in the top of the popup for "invite new user" that spawns an input inside the popup similar to the Warrant UX 
- [ ] rows contain `username` 
- [ ] rows contain `remove from topic` 
- [ ] rows contain text with the current role: `admin` / `moderator` / `participant` with a down chevron that pops up a modal to change them

**Comment by skeptrunedev** [comment]
![image](https://user-images.githubusercontent.com/15804464/226495084-d8f21402-3db4-4680-94e9-a81178ec23ef.png)

**Comment by teshler** [comment]
"Participant" was changed to "Contributor" in these completed user management buttons. They are also separate buttons.

"Invite new user" button
![image](https://user-images.githubusercontent.com/128166005/226512471-dfcdf5d0-ff7e-4ef0-abe7-f8fa7e923282.png)

"User management" button
![image](https://user-images.githubusercontent.com/128166005/226512811-fdcaec9a-0eb4-4b94-9edb-cf8acae19817.png)

**Comment by teshler** [comment]
Correction to the "Invite new user" button

![image](https://user-images.githubusercontent.com/128166005/226514189-37bdd78f-774a-48c6-a9a5-945cc4101494.png)
