### ISSUE TITLE
UI design: editing for cards 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/app#84]
Features needed for this design 

- [x] editing icon on the bottom of the statement card (while all cards will be editable, we only need to design the statement) 
- [x] When the editing icon is pressed, it switches out the card for an input form with all of the relevant text currently filled in 

Notes: 

- We will only allow editing for cards which do not have something connected to them further down the flow

**Comment by teshler** [comment]
Completed interactive editing button for cards

https://user-images.githubusercontent.com/128166005/226498296-c39342f9-7901-4c83-98df-459277187512.mp4
